spring.application.name=DevPort
# Server Port
server.port=8080

# Local PostgreSQL Database Config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.jpa.open-in-view=false
# Cap the embedded Tomcat thread pool to reduce idle memory usage
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=4


sentry.dsn=${SENTRY_DSN}
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true